package com.yrx.datasourcemanager.manager.pojo;

import java.util.Date;

public class ApiConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.id
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.data_source_id
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private Integer dataSourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.api_name
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String apiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.api_type
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String apiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.http_url
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String httpUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.http_type
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String httpType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.bill_type
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String billType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.bill_field_path
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String billFieldPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.bill_value
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String billValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.api_docs
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String apiDocs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.create_author
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String createAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.create_time
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.update_author
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private String updateAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_config.update_time
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.id
     *
     * @return the value of api_config.id
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.id
     *
     * @param id the value for api_config.id
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.data_source_id
     *
     * @return the value of api_config.data_source_id
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public Integer getDataSourceId() {
        return dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.data_source_id
     *
     * @param dataSourceId the value for api_config.data_source_id
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setDataSourceId(Integer dataSourceId) {
        this.dataSourceId = dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.api_name
     *
     * @return the value of api_config.api_name
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.api_name
     *
     * @param apiName the value for api_config.api_name
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.api_type
     *
     * @return the value of api_config.api_type
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getApiType() {
        return apiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.api_type
     *
     * @param apiType the value for api_config.api_type
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setApiType(String apiType) {
        this.apiType = apiType == null ? null : apiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.http_url
     *
     * @return the value of api_config.http_url
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getHttpUrl() {
        return httpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.http_url
     *
     * @param httpUrl the value for api_config.http_url
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setHttpUrl(String httpUrl) {
        this.httpUrl = httpUrl == null ? null : httpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.http_type
     *
     * @return the value of api_config.http_type
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getHttpType() {
        return httpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.http_type
     *
     * @param httpType the value for api_config.http_type
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setHttpType(String httpType) {
        this.httpType = httpType == null ? null : httpType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.bill_type
     *
     * @return the value of api_config.bill_type
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.bill_type
     *
     * @param billType the value for api_config.bill_type
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setBillType(String billType) {
        this.billType = billType == null ? null : billType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.bill_field_path
     *
     * @return the value of api_config.bill_field_path
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getBillFieldPath() {
        return billFieldPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.bill_field_path
     *
     * @param billFieldPath the value for api_config.bill_field_path
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setBillFieldPath(String billFieldPath) {
        this.billFieldPath = billFieldPath == null ? null : billFieldPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.bill_value
     *
     * @return the value of api_config.bill_value
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getBillValue() {
        return billValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.bill_value
     *
     * @param billValue the value for api_config.bill_value
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setBillValue(String billValue) {
        this.billValue = billValue == null ? null : billValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.api_docs
     *
     * @return the value of api_config.api_docs
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getApiDocs() {
        return apiDocs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.api_docs
     *
     * @param apiDocs the value for api_config.api_docs
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setApiDocs(String apiDocs) {
        this.apiDocs = apiDocs == null ? null : apiDocs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.create_author
     *
     * @return the value of api_config.create_author
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getCreateAuthor() {
        return createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.create_author
     *
     * @param createAuthor the value for api_config.create_author
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setCreateAuthor(String createAuthor) {
        this.createAuthor = createAuthor == null ? null : createAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.create_time
     *
     * @return the value of api_config.create_time
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.create_time
     *
     * @param createTime the value for api_config.create_time
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.update_author
     *
     * @return the value of api_config.update_author
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String getUpdateAuthor() {
        return updateAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.update_author
     *
     * @param updateAuthor the value for api_config.update_author
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setUpdateAuthor(String updateAuthor) {
        this.updateAuthor = updateAuthor == null ? null : updateAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_config.update_time
     *
     * @return the value of api_config.update_time
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_config.update_time
     *
     * @param updateTime the value for api_config.update_time
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}