package com.yrx.datasourcemanager.manager.pojo;

import java.util.Date;

public class ApiInvokeHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_invoke_history.id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_invoke_history.api_id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Integer apiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_invoke_history.is_fee
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Boolean isFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_invoke_history.param
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_invoke_history.create_time
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_invoke_history.data
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_invoke_history.id
     *
     * @return the value of api_invoke_history.id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_invoke_history.id
     *
     * @param id the value for api_invoke_history.id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_invoke_history.api_id
     *
     * @return the value of api_invoke_history.api_id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Integer getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_invoke_history.api_id
     *
     * @param apiId the value for api_invoke_history.api_id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setApiId(Integer apiId) {
        this.apiId = apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_invoke_history.is_fee
     *
     * @return the value of api_invoke_history.is_fee
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Boolean getIsFee() {
        return isFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_invoke_history.is_fee
     *
     * @param isFee the value for api_invoke_history.is_fee
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setIsFee(Boolean isFee) {
        this.isFee = isFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_invoke_history.param
     *
     * @return the value of api_invoke_history.param
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_invoke_history.param
     *
     * @param param the value for api_invoke_history.param
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_invoke_history.create_time
     *
     * @return the value of api_invoke_history.create_time
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_invoke_history.create_time
     *
     * @param createTime the value for api_invoke_history.create_time
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_invoke_history.data
     *
     * @return the value of api_invoke_history.data
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_invoke_history.data
     *
     * @param data the value for api_invoke_history.data
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}