package com.yrx.datasourcemanager.manager.pojo;

import java.util.Date;

public class ApiParamMapping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param_mapping.id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param_mapping.api_id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Integer apiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param_mapping.param_id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Integer paramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param_mapping.is_required
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Boolean isRequired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param_mapping.create_author
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private String createAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param_mapping.create_time
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param_mapping.update_author
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private String updateAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_param_mapping.update_time
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param_mapping.id
     *
     * @return the value of api_param_mapping.id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param_mapping.id
     *
     * @param id the value for api_param_mapping.id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param_mapping.api_id
     *
     * @return the value of api_param_mapping.api_id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Integer getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param_mapping.api_id
     *
     * @param apiId the value for api_param_mapping.api_id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setApiId(Integer apiId) {
        this.apiId = apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param_mapping.param_id
     *
     * @return the value of api_param_mapping.param_id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Integer getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param_mapping.param_id
     *
     * @param paramId the value for api_param_mapping.param_id
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setParamId(Integer paramId) {
        this.paramId = paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param_mapping.is_required
     *
     * @return the value of api_param_mapping.is_required
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Boolean getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param_mapping.is_required
     *
     * @param isRequired the value for api_param_mapping.is_required
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setIsRequired(Boolean isRequired) {
        this.isRequired = isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param_mapping.create_author
     *
     * @return the value of api_param_mapping.create_author
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String getCreateAuthor() {
        return createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param_mapping.create_author
     *
     * @param createAuthor the value for api_param_mapping.create_author
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setCreateAuthor(String createAuthor) {
        this.createAuthor = createAuthor == null ? null : createAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param_mapping.create_time
     *
     * @return the value of api_param_mapping.create_time
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param_mapping.create_time
     *
     * @param createTime the value for api_param_mapping.create_time
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param_mapping.update_author
     *
     * @return the value of api_param_mapping.update_author
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String getUpdateAuthor() {
        return updateAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param_mapping.update_author
     *
     * @param updateAuthor the value for api_param_mapping.update_author
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setUpdateAuthor(String updateAuthor) {
        this.updateAuthor = updateAuthor == null ? null : updateAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_param_mapping.update_time
     *
     * @return the value of api_param_mapping.update_time
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_param_mapping.update_time
     *
     * @param updateTime the value for api_param_mapping.update_time
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}