package com.yrx.datasourcemanager.manager.pojo;

import java.util.Date;

public class ParamConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_config.id
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_config.param_name
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    private String paramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_config.param_type
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    private String paramType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_config.description
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_config.create_author
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    private String createAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_config.create_time
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_config.update_author
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    private String updateAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_config.update_time
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_config.id
     *
     * @return the value of param_config.id
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_config.id
     *
     * @param id the value for param_config.id
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_config.param_name
     *
     * @return the value of param_config.param_name
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_config.param_name
     *
     * @param paramName the value for param_config.param_name
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_config.param_type
     *
     * @return the value of param_config.param_type
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_config.param_type
     *
     * @param paramType the value for param_config.param_type
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public void setParamType(String paramType) {
        this.paramType = paramType == null ? null : paramType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_config.description
     *
     * @return the value of param_config.description
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_config.description
     *
     * @param description the value for param_config.description
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_config.create_author
     *
     * @return the value of param_config.create_author
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public String getCreateAuthor() {
        return createAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_config.create_author
     *
     * @param createAuthor the value for param_config.create_author
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public void setCreateAuthor(String createAuthor) {
        this.createAuthor = createAuthor == null ? null : createAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_config.create_time
     *
     * @return the value of param_config.create_time
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_config.create_time
     *
     * @param createTime the value for param_config.create_time
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_config.update_author
     *
     * @return the value of param_config.update_author
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public String getUpdateAuthor() {
        return updateAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_config.update_author
     *
     * @param updateAuthor the value for param_config.update_author
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public void setUpdateAuthor(String updateAuthor) {
        this.updateAuthor = updateAuthor == null ? null : updateAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_config.update_time
     *
     * @return the value of param_config.update_time
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_config.update_time
     *
     * @param updateTime the value for param_config.update_time
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}