package com.yrx.datasourcemanager.manager.dao;

import com.yrx.datasourcemanager.manager.pojo.ApiConfig;
import com.yrx.datasourcemanager.manager.pojo.ApiConfigExample.Criteria;
import com.yrx.datasourcemanager.manager.pojo.ApiConfigExample.Criterion;
import com.yrx.datasourcemanager.manager.pojo.ApiConfigExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ApiConfigSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_config
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String countByExample(ApiConfigExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("api_config");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_config
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String deleteByExample(ApiConfigExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("api_config");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_config
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String insertSelective(ApiConfig record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("api_config");
        
        if (record.getDataSourceId() != null) {
            sql.VALUES("data_source_id", "#{dataSourceId,jdbcType=INTEGER}");
        }
        
        if (record.getApiName() != null) {
            sql.VALUES("api_name", "#{apiName,jdbcType=VARCHAR}");
        }
        
        if (record.getApiType() != null) {
            sql.VALUES("api_type", "#{apiType,jdbcType=VARCHAR}");
        }
        
        if (record.getHttpUrl() != null) {
            sql.VALUES("http_url", "#{httpUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getHttpType() != null) {
            sql.VALUES("http_type", "#{httpType,jdbcType=VARCHAR}");
        }
        
        if (record.getBillType() != null) {
            sql.VALUES("bill_type", "#{billType,jdbcType=VARCHAR}");
        }
        
        if (record.getBillFieldPath() != null) {
            sql.VALUES("bill_field_path", "#{billFieldPath,jdbcType=VARCHAR}");
        }
        
        if (record.getBillValue() != null) {
            sql.VALUES("bill_value", "#{billValue,jdbcType=VARCHAR}");
        }
        
        if (record.getApiDocs() != null) {
            sql.VALUES("api_docs", "#{apiDocs,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateAuthor() != null) {
            sql.VALUES("create_author", "#{createAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateAuthor() != null) {
            sql.VALUES("update_author", "#{updateAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_config
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String selectByExample(ApiConfigExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("data_source_id");
        sql.SELECT("api_name");
        sql.SELECT("api_type");
        sql.SELECT("http_url");
        sql.SELECT("http_type");
        sql.SELECT("bill_type");
        sql.SELECT("bill_field_path");
        sql.SELECT("bill_value");
        sql.SELECT("api_docs");
        sql.SELECT("create_author");
        sql.SELECT("create_time");
        sql.SELECT("update_author");
        sql.SELECT("update_time");
        sql.FROM("api_config");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_config
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ApiConfig record = (ApiConfig) parameter.get("record");
        ApiConfigExample example = (ApiConfigExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("api_config");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getDataSourceId() != null) {
            sql.SET("data_source_id = #{record.dataSourceId,jdbcType=INTEGER}");
        }
        
        if (record.getApiName() != null) {
            sql.SET("api_name = #{record.apiName,jdbcType=VARCHAR}");
        }
        
        if (record.getApiType() != null) {
            sql.SET("api_type = #{record.apiType,jdbcType=VARCHAR}");
        }
        
        if (record.getHttpUrl() != null) {
            sql.SET("http_url = #{record.httpUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getHttpType() != null) {
            sql.SET("http_type = #{record.httpType,jdbcType=VARCHAR}");
        }
        
        if (record.getBillType() != null) {
            sql.SET("bill_type = #{record.billType,jdbcType=VARCHAR}");
        }
        
        if (record.getBillFieldPath() != null) {
            sql.SET("bill_field_path = #{record.billFieldPath,jdbcType=VARCHAR}");
        }
        
        if (record.getBillValue() != null) {
            sql.SET("bill_value = #{record.billValue,jdbcType=VARCHAR}");
        }
        
        if (record.getApiDocs() != null) {
            sql.SET("api_docs = #{record.apiDocs,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateAuthor() != null) {
            sql.SET("create_author = #{record.createAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateAuthor() != null) {
            sql.SET("update_author = #{record.updateAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_config
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("api_config");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("data_source_id = #{record.dataSourceId,jdbcType=INTEGER}");
        sql.SET("api_name = #{record.apiName,jdbcType=VARCHAR}");
        sql.SET("api_type = #{record.apiType,jdbcType=VARCHAR}");
        sql.SET("http_url = #{record.httpUrl,jdbcType=VARCHAR}");
        sql.SET("http_type = #{record.httpType,jdbcType=VARCHAR}");
        sql.SET("bill_type = #{record.billType,jdbcType=VARCHAR}");
        sql.SET("bill_field_path = #{record.billFieldPath,jdbcType=VARCHAR}");
        sql.SET("bill_value = #{record.billValue,jdbcType=VARCHAR}");
        sql.SET("api_docs = #{record.apiDocs,jdbcType=VARCHAR}");
        sql.SET("create_author = #{record.createAuthor,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_author = #{record.updateAuthor,jdbcType=VARCHAR}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        ApiConfigExample example = (ApiConfigExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_config
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    public String updateByPrimaryKeySelective(ApiConfig record) {
        SQL sql = new SQL();
        sql.UPDATE("api_config");
        
        if (record.getDataSourceId() != null) {
            sql.SET("data_source_id = #{dataSourceId,jdbcType=INTEGER}");
        }
        
        if (record.getApiName() != null) {
            sql.SET("api_name = #{apiName,jdbcType=VARCHAR}");
        }
        
        if (record.getApiType() != null) {
            sql.SET("api_type = #{apiType,jdbcType=VARCHAR}");
        }
        
        if (record.getHttpUrl() != null) {
            sql.SET("http_url = #{httpUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getHttpType() != null) {
            sql.SET("http_type = #{httpType,jdbcType=VARCHAR}");
        }
        
        if (record.getBillType() != null) {
            sql.SET("bill_type = #{billType,jdbcType=VARCHAR}");
        }
        
        if (record.getBillFieldPath() != null) {
            sql.SET("bill_field_path = #{billFieldPath,jdbcType=VARCHAR}");
        }
        
        if (record.getBillValue() != null) {
            sql.SET("bill_value = #{billValue,jdbcType=VARCHAR}");
        }
        
        if (record.getApiDocs() != null) {
            sql.SET("api_docs = #{apiDocs,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateAuthor() != null) {
            sql.SET("create_author = #{createAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateAuthor() != null) {
            sql.SET("update_author = #{updateAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_config
     *
     * @mbg.generated Sun Sep 01 20:48:26 CST 2019
     */
    protected void applyWhere(SQL sql, ApiConfigExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}