package com.yrx.datasourcemanager.manager.dao;

import com.yrx.datasourcemanager.manager.pojo.ApiInvokeHistory;
import com.yrx.datasourcemanager.manager.pojo.ApiInvokeHistoryExample.Criteria;
import com.yrx.datasourcemanager.manager.pojo.ApiInvokeHistoryExample.Criterion;
import com.yrx.datasourcemanager.manager.pojo.ApiInvokeHistoryExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ApiInvokeHistorySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String countByExample(ApiInvokeHistoryExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("api_invoke_history");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String deleteByExample(ApiInvokeHistoryExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("api_invoke_history");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String insertSelective(ApiInvokeHistory record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("api_invoke_history");
        
        if (record.getApiId() != null) {
            sql.VALUES("api_id", "#{apiId,jdbcType=INTEGER}");
        }
        
        if (record.getIsFee() != null) {
            sql.VALUES("is_fee", "#{isFee,jdbcType=BIT}");
        }
        
        if (record.getParam() != null) {
            sql.VALUES("param", "#{param,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getData() != null) {
            sql.VALUES("data", "#{data,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String selectByExampleWithBLOBs(ApiInvokeHistoryExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("api_id");
        sql.SELECT("is_fee");
        sql.SELECT("param");
        sql.SELECT("create_time");
        sql.SELECT("data");
        sql.FROM("api_invoke_history");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String selectByExample(ApiInvokeHistoryExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("api_id");
        sql.SELECT("is_fee");
        sql.SELECT("param");
        sql.SELECT("create_time");
        sql.FROM("api_invoke_history");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ApiInvokeHistory record = (ApiInvokeHistory) parameter.get("record");
        ApiInvokeHistoryExample example = (ApiInvokeHistoryExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("api_invoke_history");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getApiId() != null) {
            sql.SET("api_id = #{record.apiId,jdbcType=INTEGER}");
        }
        
        if (record.getIsFee() != null) {
            sql.SET("is_fee = #{record.isFee,jdbcType=BIT}");
        }
        
        if (record.getParam() != null) {
            sql.SET("param = #{record.param,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getData() != null) {
            sql.SET("data = #{record.data,jdbcType=LONGVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("api_invoke_history");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("api_id = #{record.apiId,jdbcType=INTEGER}");
        sql.SET("is_fee = #{record.isFee,jdbcType=BIT}");
        sql.SET("param = #{record.param,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("data = #{record.data,jdbcType=LONGVARCHAR}");
        
        ApiInvokeHistoryExample example = (ApiInvokeHistoryExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("api_invoke_history");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("api_id = #{record.apiId,jdbcType=INTEGER}");
        sql.SET("is_fee = #{record.isFee,jdbcType=BIT}");
        sql.SET("param = #{record.param,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        
        ApiInvokeHistoryExample example = (ApiInvokeHistoryExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    public String updateByPrimaryKeySelective(ApiInvokeHistory record) {
        SQL sql = new SQL();
        sql.UPDATE("api_invoke_history");
        
        if (record.getApiId() != null) {
            sql.SET("api_id = #{apiId,jdbcType=INTEGER}");
        }
        
        if (record.getIsFee() != null) {
            sql.SET("is_fee = #{isFee,jdbcType=BIT}");
        }
        
        if (record.getParam() != null) {
            sql.SET("param = #{param,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getData() != null) {
            sql.SET("data = #{data,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    protected void applyWhere(SQL sql, ApiInvokeHistoryExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}