package com.yrx.datasourcemanager.manager.dao;

import com.yrx.datasourcemanager.manager.pojo.ApiInvokeHistory;
import com.yrx.datasourcemanager.manager.pojo.ApiInvokeHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ApiInvokeHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @SelectProvider(type=ApiInvokeHistorySqlProvider.class, method="countByExample")
    long countByExample(ApiInvokeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @DeleteProvider(type=ApiInvokeHistorySqlProvider.class, method="deleteByExample")
    int deleteByExample(ApiInvokeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @Delete({
        "delete from api_invoke_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @Insert({
        "insert into api_invoke_history (api_id, is_fee, ",
        "param, create_time, ",
        "data)",
        "values (#{apiId,jdbcType=INTEGER}, #{isFee,jdbcType=BIT}, ",
        "#{param,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{data,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ApiInvokeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @InsertProvider(type=ApiInvokeHistorySqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ApiInvokeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @SelectProvider(type=ApiInvokeHistorySqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="api_id", property="apiId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_fee", property="isFee", jdbcType=JdbcType.BIT),
        @Result(column="param", property="param", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="data", property="data", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<ApiInvokeHistory> selectByExampleWithBLOBs(ApiInvokeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @SelectProvider(type=ApiInvokeHistorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="api_id", property="apiId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_fee", property="isFee", jdbcType=JdbcType.BIT),
        @Result(column="param", property="param", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ApiInvokeHistory> selectByExample(ApiInvokeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @Select({
        "select",
        "id, api_id, is_fee, param, create_time, data",
        "from api_invoke_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="api_id", property="apiId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_fee", property="isFee", jdbcType=JdbcType.BIT),
        @Result(column="param", property="param", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="data", property="data", jdbcType=JdbcType.LONGVARCHAR)
    })
    ApiInvokeHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @UpdateProvider(type=ApiInvokeHistorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ApiInvokeHistory record, @Param("example") ApiInvokeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @UpdateProvider(type=ApiInvokeHistorySqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") ApiInvokeHistory record, @Param("example") ApiInvokeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @UpdateProvider(type=ApiInvokeHistorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ApiInvokeHistory record, @Param("example") ApiInvokeHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @UpdateProvider(type=ApiInvokeHistorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ApiInvokeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @Update({
        "update api_invoke_history",
        "set api_id = #{apiId,jdbcType=INTEGER},",
          "is_fee = #{isFee,jdbcType=BIT},",
          "param = #{param,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "data = #{data,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(ApiInvokeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_invoke_history
     *
     * @mbg.generated Sun Sep 01 17:14:28 CST 2019
     */
    @Update({
        "update api_invoke_history",
        "set api_id = #{apiId,jdbcType=INTEGER},",
          "is_fee = #{isFee,jdbcType=BIT},",
          "param = #{param,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ApiInvokeHistory record);
}