package com.yrx.datasourcemanager.manager.dao;

import com.yrx.datasourcemanager.manager.pojo.ApiParamMapping;
import com.yrx.datasourcemanager.manager.pojo.ApiParamMappingExample.Criteria;
import com.yrx.datasourcemanager.manager.pojo.ApiParamMappingExample.Criterion;
import com.yrx.datasourcemanager.manager.pojo.ApiParamMappingExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ApiParamMappingSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param_mapping
     *
     * @mbg.generated Mon Sep 02 00:18:58 CST 2019
     */
    public String countByExample(ApiParamMappingExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("api_param_mapping");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param_mapping
     *
     * @mbg.generated Mon Sep 02 00:18:58 CST 2019
     */
    public String deleteByExample(ApiParamMappingExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("api_param_mapping");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param_mapping
     *
     * @mbg.generated Mon Sep 02 00:18:58 CST 2019
     */
    public String insertSelective(ApiParamMapping record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("api_param_mapping");
        
        if (record.getApiId() != null) {
            sql.VALUES("api_id", "#{apiId,jdbcType=INTEGER}");
        }
        
        if (record.getParamId() != null) {
            sql.VALUES("param_id", "#{paramId,jdbcType=INTEGER}");
        }
        
        if (record.getParamZone() != null) {
            sql.VALUES("param_zone", "#{paramZone,jdbcType=TINYINT}");
        }
        
        if (record.getIsRequired() != null) {
            sql.VALUES("is_required", "#{isRequired,jdbcType=BIT}");
        }
        
        if (record.getProcessStep() != null) {
            sql.VALUES("process_step", "#{processStep,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateAuthor() != null) {
            sql.VALUES("create_author", "#{createAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateAuthor() != null) {
            sql.VALUES("update_author", "#{updateAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param_mapping
     *
     * @mbg.generated Mon Sep 02 00:18:58 CST 2019
     */
    public String selectByExample(ApiParamMappingExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("api_id");
        sql.SELECT("param_id");
        sql.SELECT("param_zone");
        sql.SELECT("is_required");
        sql.SELECT("process_step");
        sql.SELECT("create_author");
        sql.SELECT("create_time");
        sql.SELECT("update_author");
        sql.SELECT("update_time");
        sql.FROM("api_param_mapping");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param_mapping
     *
     * @mbg.generated Mon Sep 02 00:18:58 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ApiParamMapping record = (ApiParamMapping) parameter.get("record");
        ApiParamMappingExample example = (ApiParamMappingExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("api_param_mapping");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getApiId() != null) {
            sql.SET("api_id = #{record.apiId,jdbcType=INTEGER}");
        }
        
        if (record.getParamId() != null) {
            sql.SET("param_id = #{record.paramId,jdbcType=INTEGER}");
        }
        
        if (record.getParamZone() != null) {
            sql.SET("param_zone = #{record.paramZone,jdbcType=TINYINT}");
        }
        
        if (record.getIsRequired() != null) {
            sql.SET("is_required = #{record.isRequired,jdbcType=BIT}");
        }
        
        if (record.getProcessStep() != null) {
            sql.SET("process_step = #{record.processStep,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateAuthor() != null) {
            sql.SET("create_author = #{record.createAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateAuthor() != null) {
            sql.SET("update_author = #{record.updateAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param_mapping
     *
     * @mbg.generated Mon Sep 02 00:18:58 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("api_param_mapping");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("api_id = #{record.apiId,jdbcType=INTEGER}");
        sql.SET("param_id = #{record.paramId,jdbcType=INTEGER}");
        sql.SET("param_zone = #{record.paramZone,jdbcType=TINYINT}");
        sql.SET("is_required = #{record.isRequired,jdbcType=BIT}");
        sql.SET("process_step = #{record.processStep,jdbcType=VARCHAR}");
        sql.SET("create_author = #{record.createAuthor,jdbcType=VARCHAR}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_author = #{record.updateAuthor,jdbcType=VARCHAR}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        ApiParamMappingExample example = (ApiParamMappingExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param_mapping
     *
     * @mbg.generated Mon Sep 02 00:18:58 CST 2019
     */
    public String updateByPrimaryKeySelective(ApiParamMapping record) {
        SQL sql = new SQL();
        sql.UPDATE("api_param_mapping");
        
        if (record.getApiId() != null) {
            sql.SET("api_id = #{apiId,jdbcType=INTEGER}");
        }
        
        if (record.getParamId() != null) {
            sql.SET("param_id = #{paramId,jdbcType=INTEGER}");
        }
        
        if (record.getParamZone() != null) {
            sql.SET("param_zone = #{paramZone,jdbcType=TINYINT}");
        }
        
        if (record.getIsRequired() != null) {
            sql.SET("is_required = #{isRequired,jdbcType=BIT}");
        }
        
        if (record.getProcessStep() != null) {
            sql.SET("process_step = #{processStep,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateAuthor() != null) {
            sql.SET("create_author = #{createAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateAuthor() != null) {
            sql.SET("update_author = #{updateAuthor,jdbcType=VARCHAR}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_param_mapping
     *
     * @mbg.generated Mon Sep 02 00:18:58 CST 2019
     */
    protected void applyWhere(SQL sql, ApiParamMappingExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}