package com.yrx.datasourcemanager.manager.dao;

import com.yrx.datasourcemanager.manager.pojo.ParamConfig;
import com.yrx.datasourcemanager.manager.pojo.ParamConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ParamConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @SelectProvider(type=ParamConfigSqlProvider.class, method="countByExample")
    long countByExample(ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @DeleteProvider(type=ParamConfigSqlProvider.class, method="deleteByExample")
    int deleteByExample(ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @Delete({
        "delete from param_config",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @Insert({
        "insert into param_config (param_name, param_type, ",
        "description, create_author, ",
        "create_time, update_author, ",
        "update_time)",
        "values (#{paramName,jdbcType=VARCHAR}, #{paramType,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{createAuthor,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateAuthor,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ParamConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @InsertProvider(type=ParamConfigSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ParamConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @SelectProvider(type=ParamConfigSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="param_name", property="paramName", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_type", property="paramType", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_author", property="createAuthor", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_author", property="updateAuthor", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ParamConfig> selectByExample(ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @Select({
        "select",
        "id, param_name, param_type, description, create_author, create_time, update_author, ",
        "update_time",
        "from param_config",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="param_name", property="paramName", jdbcType=JdbcType.VARCHAR),
        @Result(column="param_type", property="paramType", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_author", property="createAuthor", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_author", property="updateAuthor", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    ParamConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @UpdateProvider(type=ParamConfigSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ParamConfig record, @Param("example") ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @UpdateProvider(type=ParamConfigSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ParamConfig record, @Param("example") ParamConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @UpdateProvider(type=ParamConfigSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ParamConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_config
     *
     * @mbg.generated Sun Sep 01 18:07:46 CST 2019
     */
    @Update({
        "update param_config",
        "set param_name = #{paramName,jdbcType=VARCHAR},",
          "param_type = #{paramType,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "create_author = #{createAuthor,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_author = #{updateAuthor,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ParamConfig record);
}